### ISSUE TITLE
Tunnel Bores: 1.20.6 version has duplication bug

### ISSUE THREAD

**Issue by Bloo-dev** [Gamemode4Dev/GM4_Datapacks#1009]
**Describe the bug**
Tunnel Bores' 1.21 version had a duplication bug where coal and rails were not correctly removed from the chest minecart's inventory once the final item is reached. This bug likely also affects the 1.20.6 version. Confirmation needed.

**To Reproduce**
1. Place a Tunnel Bore, including a Chest Minecart
2. Place a single rail and coal into the Chest Minecart
3. Start the Tunnel Bore
4. Note how the items are not used up.

**Expected behavior**
The items should be used up.

**Fix**
This is due to an item count of  `0` being invalid as of 1.20.6, therefore the command fails. An explicit item delete command needs to be added tot he count `0` case.

**Comment by BluePsychoRanger** [comment]
Fixed in commit 26034bc
https://github.com/Gamemode4Dev/GM4_Datapacks/commit/26034bc34ec1a143d9986c50017b3a6800581711

**Comment by misode** [comment]
@BluePsychoRanger That commit was only made to `master` after `ver/1.20.5` was created. This is still an issue in 1.20.5/6

**Comment by BluePsychoRanger** [comment]
I see. My bad. How do we push changes to other branches?

**Comment by Bloo-dev** [comment]
This should now be fixed in 1.20.5/1.20.6.
